### ISSUE TITLE
Update curations based on curation snapshot from GCI

### ISSUE THREAD

**Issue by yugen** [clingen-data-model/clingen-gene-tracker#2]
Import info
- [x] HGNC ID and MONDO ID make a unique dyad; use to match curations for initial import
- [x] Add gdm_uuid to curations table and store for direct link to GCI record
- [x] Add creator_uuid to users table and capture during import for direct link to GCI record
- [x] Add gci_affiliation_id to expert_panels and capture during import for direct link to GCI
- [x] Add modes_of_inheritance table and foreign_key to curations so we can match.
  * Include HP id (human phenotype ontology)
- [x] Status "None" maps to our Uploaded in curations_statuses.
- [x] ~~For any creator that doesn't exist in our system create curator user and mark deactivated.  DO NOT SEND WELCOM EMAIL.~~
- [x] Produce list of any HGNCID/MONDOID dyads that don't match our records grouped by ExpertPanel (affiliation) for clean up.
- [ ] Courtney getting coordinators to update records so we move forward.

Acceptance Criteria:

* Update existing curations based on data from GCI snapshot produced first week of Feb 2020

**Comment by yugen** [comment]
@courtneythaxton I've worked around the affiliations/expert panels/working groups issues and have finished the script that imports the data from the GCI curation snapshot we received from Gloria.  

Here's where we stand by the numbers:
- The csv file has 1083 rows
- 708 appear to update their corresponding curations without error.
- 371 can't be matched by HGNC ID/MonDO ID.  I have a list that includes hgnc_id, mondo_id, curator email, and affiliation name in json format that I can transform into anything you'd like.
- 4 has a MOI of 'Other' which I'm unable to match to the list of MOI values I pulled directly from the 
- 9 have an MOI "Undetermined mode   of inheritance (HP:0000005)" which seems to be a misinterpretation of the HP Ontology. HP:0000005 is the top level class 'Mode Of Inheritance' of which all other modes of inheritance are subclasses. Maybe there's some practical reason to use that but I'll need you to tell me how you'd like to handle it.
- By creating new curator users for curators we don't have in our system we ended up with 7 instances where there are 2 users with the same name, but separate email addresses.

Note that there are overlaps in the 3 classes of errors I've listed above which is why the sum of the errors and successes don't match the total numer of rows.

These errors also don't account for instances in which data was missing from a row (i.e. missing affiliation id, curator info, classification, status, etc.

Shall we plan to go over this on Monday during our scheduled meeting since you're out tomorrow?

**Comment by courtneythaxton** [comment]
hi @yugen thank you for this review. I'm glad to see that ~70% of the records corresponded!

For the 371, would you please put that in an excel file, and I can look them over and try to find some answers!

We do have the option of "other" on MOI, however these records cannot be published unless the MOI is updated. Nevertheless, it would be good for us to include this option in the Tracker to correspond. 

Good question on the MOI of "undetermined MOI." You are correct in that this title "undetermined MOI" does not match the HPO term. However, we did this intentionally. HPO was not so keen on making an ID for undetermined, so the suggestion was to use the parent term for all MOIs. It is rare that we use this but it was needed for some curation to be published. Would we be able to set up the system so that overtime HP:0000005 (MOI) is used it translate it to "undetermined MOI?"

Could you please let me know the names and information for the 7 double dippers ;) I do know that  we do have 2 Kristy Lee's and they are different people! For the others I may be able to investigate or provide info.

I think it would be good to review in our meeting on Monday. I can try to look at some items ahead of time if needed. I do have a practice run of my interactive workshop on Monday too, that I will be working on this weekend, but hope to review all these items sometime this next week!

**Comment by yugen** [comment]
@courtneythaxton 

- I'll add 'Other' and 'HP:0000005 - Undertermined MOI' to our list of MOIs
- Attached is an excel file of by the unmatched gci records and the "duplicated" users

[gci_snapshot_issues.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4236668/gci_snapshot_issues.xlsx)

**Comment by courtneythaxton** [comment]
@yugen For the 371 records that are not currently in the GeneTracker, would we be able to use the data we have from the GCI snapshot to upload the info? Similar to a bulk upload from the beginning?

some of these groups are ones that have not maintained or kept up with some of their gene lists, others were finished with their efforts before we even had the GeneTracker. 

I just wanted to get a sense of what we could do once I look through them?

Thanks!
@courtneythaxton

**Comment by courtneythaxton** [comment]
@yugen So I think I see one issue that might be arising from this gene list. Many are present in the tracker, however the discrepancy comes on the assigned curator differing between the tracker and the GCI record. 

Would a difference in this cause a problem with automation?

If so, would we be able to allow multiple individuals to be assigned to a curation in the tracker? 

Thanks!

**Comment by yugen** [comment]
@courtneythaxton Here's an adjusted list of missing curations after matching with hgnc_id and curator email.  Looks like that only resolved a about 15:

[adjusted_missing_curations.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4238296/adjusted_missing_curations.xlsx)

**Comment by courtneythaxton** [comment]
@yugen I have one more request. Would you be able to add the gene symbol on the excel sheet? I think this would allow the coordinators to locate the records faster, as the search box does not currently work for HGNC ID in the gene Tracker.

Thanks!

**Comment by yugen** [comment]
Here's an updated csv with gene symbol:

[gci_snapshot_missing.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4256220/gci_snapshot_missing.xlsx)

**Comment by yugen** [comment]
@courtneythaxton attached you'll find the spreadsheet we discussed yesterday for linking our EPs and WGs to Affiliations.  I've added an Affiliations tab for reference.

https://docs.google.com/spreadsheets/d/1QdKFD7o6wGG8o84-G_4J7Aa00aBV3suGu-efAHkdt38/edit#gid=121352689

**Comment by courtneythaxton** [comment]
hi @yugen I went through the snapshot list and found that there are some records we can ignore. This is because either they do not have an affiliation at this time, or they are part of an external curation group, and this information will not be published on the website in its current form.

If we wanted we could consider a "No affiliation" group for all of these similar to the GC, but we can talk about this at a later date. Especially since these curations do not count towards milestones.

Please let me know if you have any other questions.

[gci_snap-shot_2-26-20_records to ignore.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4258339/gci_snap-shot_2-26-20_records.to.ignore.xlsx)

**Comment by courtneythaxton** [comment]
@yugen here is an updated records to ignore from the cci snapshot at this time.

[gci_snap-shot_2-26-20_records to ignore.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4259312/gci_snap-shot_2-26-20_records.to.ignore.xlsx)

**Comment by yugen** [comment]
After ignoring the records in the previously attached xlsx and testing the import against fresh data from production we have 244 records from the GCI that can't be matched.

[gci_snapshot_missing.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4282682/gci_snapshot_missing.xlsx)

**Comment by courtneythaxton** [comment]
Thanks TJ! I will get back to the coordinators and see where they are with the import of data.

**Comment by courtneythaxton** [comment]
Hi @yugen, I got word from all the coordinators that they have updated their records in the Gene tracker based on the snapshot we received in February.

Hopefully we will have all records taken care of except for the few that we knew to ignore.

Would we be able to see the remaining genes?

Also, I got the go ahead from the Gene Curation small WG to update the workflow to ask coordinators to enter in MonDO IDs into the gene tracker ahead of the GCI. They agreed on the current workflow mock up that you proposed as the likely way to deal with records that do not match.

**Comment by courtneythaxton** [comment]
@yugen I went through our previous cci_snapshot_missing_2 worksheet and all the remaining curations of interest have been updated. There are ~55 on that list that will be ignored and I believe they overlap with the prior sheet, although I had not checked thoroughly.

Hopefully this narrows down the list even more. 

I think at this time, we would be ready to go, and just settle on the weekly email to coordinators to update records.

I will be giving a presentation April 9 about procuration, the new workflow and the gene tracking system, so it would be good to let me know if we have any updates to give on the automation at that time so I can highlight them

**Comment by yugen** [comment]
@courtneythaxton Here's the updated list.  We're down to 77 missing!  

Let me know which if any we can ignore.

Here's the updated xlsx:
[gci_snapshot_missing.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4371124/gci_snapshot_missing.xlsx)

**Comment by yugen** [comment]
@courtneythaxton Just checking in on this. Have you had a chance to review the 77 missing records in the attached spreadsheet above?  I'd love to put this issue to bed and start ingesting data from the GCI via the data exchage.

**Comment by courtneythaxton** [comment]
Hi @yugen I went through the records and have given notes or updates.

For the bright and light yellow cells those are either records to ignore due to no affiliation in the GCI, or because they are from an external group respectively.

For the gray records I have made corrections.

For the Blue records, I have made corrections but there may be questions on our logic or how the GCI and Gene Tracker records will link.

For the white records, there are currently records in the Gene tracker that are the same info as the GCI, so I"m not sure what is going on but I put the data I have or questions!

Please let me know if you need anything else.

**ONE consideration we may need to add is that GCI records are gene-disease-mode of inheritance, so this may be an additional way we parse the records coming in aside from affiliation. This is important for the genes like Col11A2 on the list that have 4 records from hearing loss in which 2 Paris each have the same gene ID and MONDO ID, but what differs in the mode of inheritance (MOI).**
[gci_snapshot_missing-3_ct edits.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4411101/gci_snapshot_missing-3_ct.edits.xlsx)

**Comment by yugen** [comment]
@courtneythaxton up till now the GeneTracker hasn't known anything about MOI.  This means that we are not able to consider MOI when determining identity between GT records and GCI records.  This seems like a pretty significant hole that we're going to have to plug.  

Considering this I looked at the code and determined that the import grabs the first HGNC/MonDO match even if there are multiple.  When I check for multiples there are 32 GCI records that have ambiguous matches in the GT.  I've attached a spreadsheet of those.

[gci_snapshot_ambiguous.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4416206/gci_snapshot_ambiguous.xlsx)

I was able to fix a couple of items that you said were in the GT but weren't matching.  Turns out it was badly formatted mondo ids.  I've added some logic to enforce mondo id formatting going forward so that shouldn't be a problem in the future.

The four remaining 'missing' records:
- Are using free text for the disease (LIG1, ACTG1) - Trying to match disease based on free text that doesn't match EXACTLY will be costly and unlikely to produce results we can have confidence in.  The only practical solution I can think of at this point is to manually add the GCI UUID to these records and sync them up based on that identifier.
- Have data that has changed or should change in the GCI (GCH1, MYOC) - Unfortunately, updated data in GCI doesn't help us with the snapshot since we only have data as it existed on the day Glora created the snapshot. I think for now we should ignore these GCI records for now and wait for update the update messages that should be in the GCI event stream from the steaming server.

Let me know what you think.  It might be easier to discuss on the phone, which I'm happy to do if you agree.

**Comment by courtneythaxton** [comment]
Hi @yugen 
I agree with what you have stated above for the records in question (4 remaining). 

As for the Mode of inheritance, I thought we did have this listed to  include on the tracking system, albeit it may have not been prioritized or included. The GCI snapshot and data will contain this info in the future. 

I agree that each of these records would have a different UUID, so that would also potentially be a reason to "Create" a new record, or at least flag the record for the coordinators of each group in the weekly email. 

I understand this is a new issue, and really up until this point, we only have 2 examples of this occurring, so much less then would be expected. We tried our best to think of all scenarios, and for the most part I think ew are doing really well!

At the end of the day if we redirect the users to use this platform first, then it will certainly happen more smoothly! And many coordinators are supporting this new workflow and likely to be vocal about it which is a plus.

**Comment by yugen** [comment]
@courtneythaxton Here's a spreadsheet of GT records that need to be disambiguated due to MOI.  I've included columns for both MOI and UUID.  I'll let you decide which of those you want to fill in, just please choose one or the other.

Not included in this list is OTC, but it's worth noting that we are getting two records with that gene/disease pair from the GCI but only 1 record in the GeneTracker (though there are 2 other GT records that don't have a MONDO ID).  I'm not sure we've sufficiently resolved this issue.

[gene_tracker_records_need_disambiguation.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4422113/gene_tracker_records_need_disambiguation.xlsx)

Feel free to ping me if you have any questions.

**Comment by courtneythaxton** [comment]
Hi @yugen 

Disambiguated...... or maybe added a little more ambiguity, you decide ;)

[gene_tracker_records_need_disambiguation_CT.xlsx](https://github.com/clingen-data-model/clingen-gene-tracker/files/4423688/gene_tracker_records_need_disambiguation_CT.xlsx)

**Comment by yugen** [comment]
@courtneythaxton The GCI snapshot has been imported into the production database! 🎉

**Comment by courtneythaxton** [comment]
@yugen this is great news!!
